name: Run Go Script

on:
  workflow_dispatch: # GitHubの画面から手動で実行できるようにする設定

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのコードを取得
        uses: actions/checkout@v4

      - name: Go環境の準備
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Goプログラムの実行
        run: go run main.go
